# Site settings
title: Bike GPS - Ride tracker app
email: support@bikegps.app
author: Innostart Kft.
description:
url: https://bikegps.app
baseurl: /

# Build settings
markdown: kramdown
permalink: :title/
sass:
  sass_dir: css
  style: compressed
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
plugins:        
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - readme_files
  - README.md
  - CNAME

appstoreid: 1450105816
